version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
    - checkout
    - run:
        name: Add Firebase Credentials
        command: echo $FIREBASE_KEY > credentials.json
    - run:
        name: Build Docker Image
        command: |
          docker login ghcr.io -u rohit-karthik -p $REGISTRY_PASSWORD
          docker build -t ghcr.io/redworth/humidifier-project-server:latest .
    - run:
        name: Push Docker Image
        command: docker push ghcr.io/redworth/humidifier-project-server:latest
  deploy:
    machine:
      image: ubuntu-2004:202101-01
    steps:
    - checkout
    - kubernetes/install-kubectl
    - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
    - run:
        name: Restart Deployment (does rolling update with same image pulled, which will be the new latest image)
        command: |
          kubectl rollout restart deployment/iot-backend
   
workflows:
  Build and Deploy:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
    - deploy:
        filters:
          branches:
            only:
            - master
        requires:
        - build
    
    
        
