version: 2.1

jobs:
  build:
    docker:
    - image: python:3.9
    resource_class: small
    steps:
    - checkout
    - run:
        name: Add Firebase Credentials
        command: echo $FIREBASE_KEY > credentials.json
    - run:
        name: Build Docker Image
        command: |
          docker login ghcr.io -u rohit-karthik -p $REGISTRY_PASSWORD
          docker build -t ghcr.io/redworth/humidifier-project-server:latest .
    - run:
        name: Push Docker Image
        command: docker push ghcr.io/redworth/humidifier-project-server:latest
  deploy:
    docker:
    - image: python:3.9
    resource_class: small
    steps:
    - run:
        name: Add SSH Keys
        command: |
          mkdir -p ~/.ssh/
          echo $SSH_KEY > ~/.ssh/github_ssh.key
          sudo chmod 600 ~/.ssh/github_ssh.key
          eval "$(ssh-agent)"
          ssh-add ~/.ssh/github_ssh.key
          ssh-keyscan redworth-linux-vm-1.westus2.cloudapp.azure.com >> ~/.ssh/known_hosts
    - run:
        name: Docker Login
        command: ssh -i ~/.ssh/github_ssh.key ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'cat ~/docker_login.txt | sudo docker login ghcr.io --username rohit-karthik --password-stdin'
    - run:
        name: Pull Image
        command: ssh -i ~/.ssh/github_ssh.key ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'sudo docker pull ghcr.io/redworth/humidifier-project-server:latest'
    - run:
        name: Remove Existing Containers
        command: ssh -i ~/.ssh/github_ssh.key ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'if [ "$(sudo docker ps -a -q)" != "" ]; then sudo docker rm --force $(sudo docker ps -a -q); fi'
    - run:
        name: Run New Container
        command: ssh -i ~/.ssh/github_ssh.key ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'sudo docker run -d -p 80:8000 ghcr.io/redworth/humidifier-project-server:latest'
   
   workflows:
    Build and Deploy:
      jobs:
      - build
      - deploy:
          requires:
          - build
    
    
        
