name: Build and Deploy
on:
  schedule:
  - cron: 0 10 * * *
  - cron: 0 18 * * *
  workflow_dispatch:
jobs:
  build:
    name: Build/Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: docker build -t humidifier-project-server:latest . 
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: redworth/humidifier-project-server/humidifier-project-server
          tag_with_ref: true
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ssh ${{secrets.SSH_USERNAME}}:${{secrets.SSH_PASSWORD}}@${{secrets.SSH_SERVER}} | ls
      - name: SSH Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: cat docker_login.txt | sudo docker login ghcr.io -u rohit-karthik --password-stdin
      - name: SSH Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: sudo docker pull ghcr.io/redworth/humidifier-project-server:latest
      - name: SSH Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            if [ "$(sudo docker ps -a -q)" != "" ]
            then
            sudo docker rm --force $(sudo docker ps -a -q)
            fi
      - name: SSH Script
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.SSH_SERVER }}
           username: ${{ secrets.SSH_USERNAME }}
           password: ${{ secrets.SSH_PASSWORD }}            
           port: 22
           script: sudo docker run -d -p 80:8000 ghcr.io/redworth/humidifier-project-server:latest
            
