# This is a basic workflow to help you get started with Actions

name: Merge to Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "0 3 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      env:
        GITHUB_WORKSPACE: /
    - name: Action-Automerge
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        # Token to authenticate with GitHub
        github_token: 4f7b2f5520f8af247df4b61e7c5adb0313d21699
        # Source branch you want to merge into the target.
        source: 'all_code'
        # Target branch, where the source branch is going to be merged into
        target: 'master'
