name: Build and Deploy
on:
  schedule:
  - cron: 0 10 * * *
  - cron: 0 18 * * *
  workflow_dispatch:
jobs:
  build:
    name: Build/Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - run: echo secrets.FIREBASE_CERT > credentials.json
    - run: docker login ghcr.io -u rohit-karthik -p ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker build -t humidifier-project-server:latest .
    - run: docker push humidifier-project-server:latest
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ../github_ssh.key
        sudo chmod 600 ../github_ssh.key
    - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}
    - run: ls
