name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_KEY: ${{ secrets.FIREBASE_CERT }}
    steps:
    - run: echo $FIREBASE_KEY > credentials.json
    - run: cat credentials.json
